name: SiGuitars
favicon: null
layout_spectrum: 0.75391
typography_spectrum: 0.24368
title: One of a kind custom and handmade guitars for true guitar lovers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#a5a5a5'
    - '#242424'
    - '#525252'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
